apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    type: firstapp
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: first-app
        image: smritisamarth/firstimage:20
        ports:
        - containerPort: 80
